const axios = require("axios");
const cheerio = require("cheerio");

const igstalk = (name) =>
  new Promise((resolve, reject) => {
    axios
      .get(`https://dumpor.com/v/${name}`, {
        headers: {
          cookie:
            "__atuvc=3%7C32%2C0%7C33%2C0%7C34%2C7%7C35;__atuvs=631308a185e3b6a8002;__gads=ID=e13c220cd831e27f-229b3eaa94d5007b:T=1660299588:RT=1660299588:S=ALNI_MZkZ8EpzVmpraeGFNxskZKAZydR-A;__gpi=UID=0000088a1970d6b5:T=1660299588:RT=1662188665:S=ALNI_MaxRWATvLc8pPy6ykXXR0uHWvJRvA;_inst_key=SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYVG1QNjA5NWtTODhLWjZCZXZZdWN3WU43.84EoZHfprCX2SvAXIyj--82C-xM40zoxpNyU56nXxYo;_ym_d=1660299588;_ym_isad=2;_ym_uid=1660299588402037491;",
          "user-agent":
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
        },
      })
      .then((response) => {
        const html = response.data;
        const C = cheerio.load(html);
        const name = C(".user__title").find("h1").text();
        const username = C(".user__title").find("h4").text();
        const pp = C("div.user__img")
          .attr("style")
          ?.replace("background-image: url('", "")
          .replace("');", "");
        const desc = C(".user__info-desc").text();
        const post = C("ul.list > :nth-child(1)")
          .text()
          .replace("Posts", "")
          .trim();
        const followers = C("ul.list > :nth-child(2)")
          .text()
          .replace("Followers", "")
          .trim();
        const following = C("ul.list > :nth-child(3)")
          .text()
          .replace("Following", "")
          .trim();
        const result = {
          name,
          username,
          desc,
          post,
          followers,
          following,
          pp,
        };
        resolve(result);
      })
      .catch((err) => {
        reject(err);
      });
  });
const igstalkv2 = (name) =>
  new Promise((resolve, reject) => {
    axios
      .get("https://www.pixwox.com/profile/jokowi/", {
        headers: {
          cookie:
            "__qca=I0-562846536-1663360605814;__unid=09d636cf-153f-19d9-b543-efd260a4bbb0;_cc_id=4169bd3c932f870a080e0c6f307a9091;_ga=GA1.1.2078446576.1663335673;_ga_YGP7JJQJHY=GS1.1.1663369951.3.1.1663370054.0.0.0;_gid=GA1.2.1122337187.1663335673;_lr_env_src_ats=false;_lr_retry_request=true;_pbjs_userid_consent_data=3524755945110770;cto_bidid=FFcrM19iWTZzRUFXR1BrdVhNd25XRFBPc2hLY1dZUXZVMyUyRkRzR1dibktsbGdObGQlMkJxdnRBekdHanV1ZyUyQlF4WSUyQnRTSmZjU0pDQ0UlMkY3QllqdTk0dWhiWnhFOGljbnlCU24wUVBVT3NwVyUyQmJUQTFwQSUzRA;cto_bundle=V2Y0yF9QV1NxOSUyQlJCNmh1MlFOTnc2M3dWYzYlMkZtdTluSW5qY2FKcVZ2JTJGQUR0VVFpRXU0c3NNajA2R2t4SDBVM1M5UElLRDRPV05aYzFPZFB5TUZGdVdhOEcyVEZNQlMlMkJpZTNxTmx5QjRHT25nVDNGYWxtNkVPaVlmQTBMOTJud2JGZkd6d21jM2dWeFVlendKQVEwV21pRWhmQSUzRCUzRA;panoramaId_expiry=1663422078742;pbjs-unifiedid=%7B%22TDID%22%3A%22f1c61751-28e4-4dc2-adc6-2e6138ddbc5f%22%2C%22TDID_LOOKUP%22%3A%22TRUE%22%2C%22TDID_CREATED_AT%22%3A%222022-08-16T13%3A41%3A23%22%7D;pbjs-unifiedid_last=Fri%2C%2016%20Sep%202022%2023%3A14%3A19%20GMT;sharedid=acb91de4-8043-4683-bcae-5585dec6e59d;",
          "user-agent":
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
        },
      })
      .then((response) => {
        const html = response.data;
        const C = cheerio.load(html);
        const username = C("body").find(".username").text();
        console.log(username);
      })
      .catch((err) => {
        reject(err.message);
      });
  });
module.exports = igstalk;

// Semicolon separated Cookie File
// This file was generated by EditThisCookie
// Details: http://www.ietf.org/rfc/rfc2109.txt
// Example: http://www.tutorialspoint.com/javascript/javascript_cookies.htm
